// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;


arma::mat prime_core(arma::mat x, arma::mat C, arma::mat sc_data, double min_nbr, double max_nbr);
RcppExport SEXP _PRIME_prime_core(SEXP xSEXP, SEXP CSEXP, SEXP sc_dataSEXP, SEXP min_nbrSEXP, SEXP max_nbrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sc_data(sc_dataSEXP);
    Rcpp::traits::input_parameter< double >::type min_nbr(min_nbrSEXP);
    Rcpp::traits::input_parameter< double >::type max_nbr(max_nbrSEXP);
    rcpp_result_gen = Rcpp::wrap(prime_core(x, C, sc_data, min_nbr, max_nbr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PRIME_prime_core", (DL_FUNC) &_PRIME_prime_core, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PRIME(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
