# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prime_core <- function(x, C, sc_data, min_nbr, max_nbr) {
    .Call('_PRIME_prime_core', PACKAGE = 'PRIME', x, C, sc_data, min_nbr, max_nbr)
}
